// Code generated by "stringer -linecomment -type=Coffee"; DO NOT EDIT.

package coffee

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Drip-0]
	_ = x[Latte-1]
	_ = x[Breve-2]
	_ = x[Cappuccino-3]
}

const _Coffee_name = "drip coffeelattebrevecappuccino"

var _Coffee_index = [...]uint8{0, 11, 16, 21, 31}

func (i Coffee) String() string {
	if i < 0 || i >= Coffee(len(_Coffee_index)-1) {
		return "Coffee(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Coffee_name[_Coffee_index[i]:_Coffee_index[i+1]]
}
